// Database version: 2025-02-03-v3 (FORCE UPDATE)
export interface ScamEntry {
  url: string
  type: string
  description: string
  severity: "high" | "medium" | "critical"
  reports: number
  lastReported: string
}

export const scamDatabase: ScamEntry[] = [
  // Recently Added Critical Threats
  {
    url: "https://minepihub.com",
    type: "Typosquatting",
    description: "Impersonates official minepi.com domain to steal user credentials",
    severity: "critical",
    reports: 5234,
    lastReported: "1 hour ago",
  },
  {
    url: "https://giftnetpi2025.com/wallet.php",
    type: "Giveaway Scam",
    description: "Fake 2025 gift promotion harvesting wallet credentials",
    severity: "critical",
    reports: 4876,
    lastReported: "2 hours ago",
  },
  {
    url: "https://giftnetpi2025.com/",
    type: "Giveaway Scam",
    description: "Main landing page for fake 2025 Pi gift promotion phishing campaign",
    severity: "critical",
    reports: 4876,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pimarket-tradingspot.vercel.app",
    type: "Fake P2P Market",
    description: "Fraudulent P2P marketplace stealing wallet credentials",
    severity: "high",
    reports: 3234,
    lastReported: "3 hours ago",
  },

  // Pi 914 Gift Scams
  {
    url: "https://pi914gift.com/claim",
    type: "Giveaway Scam",
    description: "Fake 914 Pi token gift promotion phishing for credentials",
    severity: "critical",
    reports: 4123,
    lastReported: "2 hours ago",
  },
  {
    url: "https://914pigift.net/wallet.php",
    type: "Phishing Site",
    description: "Phishing site impersonating 914 Pi event with wallet credential harvesting",
    severity: "critical",
    reports: 4567,
    lastReported: "4 hours ago",
  },
  {
    url: "https://claim914pi.com",
    type: "Fake Airdrop",
    description: "Fraudulent claim portal for 914 Pi token distribution",
    severity: "high",
    reports: 3345,
    lastReported: "7 hours ago",
  },

  // High-Priority Wallet Phishing
  {
    url: "https://claim314pitoken.com/wallet/",
    type: "Phony Wallet",
    description: "Fake wallet site designed to steal Pi Network passphrases and credentials",
    severity: "high",
    reports: 1847,
    lastReported: "2 hours ago",
  },
  {
    url: "https://stakepinet.com/wallet.php",
    type: "Fake Staking",
    description: "Fake staking platform promising unrealistic returns to steal credentials",
    severity: "high",
    reports: 3421,
    lastReported: "5 hours ago",
  },
  {
    url: "https://pi-wallet-unlock.com",
    type: "Phishing Site",
    description: "Fake wallet unlock service stealing recovery phrases",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pinetwork-claim.com/wallet",
    type: "Phony Wallet",
    description: "Impersonates official Pi wallet to harvest credentials",
    severity: "critical",
    reports: 4234,
    lastReported: "3 hours ago",
  },

  // KYC Scams
  {
    url: "https://www.2fa-pinet.com/2fa",
    type: "Fake 2FA",
    description: "Fraudulent 2FA verification page attempting to capture authentication codes",
    severity: "high",
    reports: 2156,
    lastReported: "1 hour ago",
  },
  {
    url: "https://kyc-pi-network.com/verify",
    type: "Fake KYC",
    description: "Fraudulent KYC verification site stealing personal documents",
    severity: "critical",
    reports: 6234,
    lastReported: "30 minutes ago",
  },
  {
    url: "https://pi-kyc-priority.com",
    type: "Fake KYC",
    description: "Fake priority KYC service stealing identity documents",
    severity: "critical",
    reports: 5123,
    lastReported: "2 hours ago",
  },

  // Telegram Bots
  {
    url: "https://t.me/PiWalletUnlockBot",
    type: "Telegram Bot",
    description: "Fake Telegram bot claiming to unlock Pi wallets",
    severity: "high",
    reports: 4567,
    lastReported: "4 hours ago",
  },
  {
    url: "https://t.me/PiKYCPriorityBot",
    type: "Telegram Bot",
    description: "Fraudulent bot offering priority KYC verification",
    severity: "critical",
    reports: 5234,
    lastReported: "2 hours ago",
  },
  {
    url: "https://t.me/OfficiaiSSafeguardBot",
    type: "Telegram Bot",
    description: "Malware-injecting verification bot stealing private keys",
    severity: "critical",
    reports: 6789,
    lastReported: "1 hour ago",
  },
  {
    url: "https://t.me/PiCoreTeamSupportBot",
    type: "Telegram Bot",
    description: "Impersonates official Pi Core Team support to steal credentials",
    severity: "critical",
    reports: 5678,
    lastReported: "3 hours ago",
  },
  {
    url: "https://t.me/pilegit1388",
    type: "Telegram Bot",
    description: "Fraudulent Telegram bot impersonating legitimate Pi services",
    severity: "high",
    reports: 3456,
    lastReported: "2 hours ago",
  },
  {
    url: "https://t.me/wrappedpi_bot",
    type: "Telegram Bot",
    description: "Fraudulent wrapped Pi bot stealing wallet credentials",
    severity: "critical",
    reports: 4876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://t.me/pi-network-official-bot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://t.me/pi-network-bot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://t.me/pi-bot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://t.me/pinetworkbot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },

  // Fake Exchanges & P2P
  {
    url: "https://pi-exchange.net/trade",
    type: "Fake Exchange",
    description: "Fraudulent exchange platform stealing deposits",
    severity: "high",
    reports: 3456,
    lastReported: "6 hours ago",
  },
  {
    url: "https://pinetwork-p2p.com",
    type: "Fake P2P Market",
    description: "Fake peer-to-peer marketplace harvesting wallet data",
    severity: "high",
    reports: 2987,
    lastReported: "5 hours ago",
  },
  {
    url: "https://tradepicoin.net",
    type: "Fake Exchange",
    description: "Fraudulent trading platform for Pi cryptocurrency",
    severity: "high",
    reports: 3234,
    lastReported: "7 hours ago",
  },
  {
    url: "https://piconvert.net/unlock%20wallet%20-%20pinet",
    type: "Phishing Site",
    description: "Fake wallet unlock service harvesting recovery phrases",
    severity: "critical",
    reports: 4876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.pi-airdrop.net/wallet.html",
    type: "Fake Airdrop",
    description: "Phishing airdrop site harvesting wallet credentials",
    severity: "critical",
    reports: 6234,
    lastReported: "1 hour ago",
  },
  {
    url: "https://www.pi-airdrop.net/",
    type: "Fake Airdrop",
    description: "Main phishing domain for fake Pi airdrop scam",
    severity: "critical",
    reports: 6234,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pimarket.my.id/unlock/",
    type: "Fake P2P Market",
    description: "Indonesian Pi market phishing site",
    severity: "high",
    reports: 3987,
    lastReported: "4 hours ago",
  },
  {
    url: "https://optionpip2p.com/",
    type: "Fake P2P Market",
    description: "Fraudulent P2P options platform stealing credentials",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.activateoptiontab.com/",
    type: "Phishing Site",
    description: "Fake option tab activation stealing credentials",
    severity: "high",
    reports: 3678,
    lastReported: "5 hours ago",
  },
  {
    url: "https://piopened.com/",
    type: "Phishing Site",
    description: "Deceptive domain phishing for Pi wallet access",
    severity: "high",
    reports: 3987,
    lastReported: "4 hours ago",
  },
  {
    url: "https://pigate.in/",
    type: "Phishing Site",
    description: "Indian-targeted Pi phishing gateway",
    severity: "high",
    reports: 3456,
    lastReported: "6 hours ago",
  },
  {
    url: "https://global-pi-market.onrender.com/",
    type: "Fake P2P Market",
    description: "Fraudulent global Pi marketplace stealing wallet access",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://minepidex.com/",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://minepidex.com",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "http://minepidex.com",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "minepidex.com",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "minepidex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network DEX platform that steals wallet credentials and funds",
    reports: 4521,
    lastReported: "2025-02-01",
  },

  // Giveaway & Airdrop Scams
  {
    url: "https://pi-airdrop2025.com",
    type: "Fake Airdrop",
    description: "Fake 2025 airdrop event phishing for wallet access",
    severity: "high",
    reports: 4123,
    lastReported: "4 hours ago",
  },
  {
    url: "https://freepigiveaway.com",
    type: "Giveaway Scam",
    description: "Fake giveaway requiring wallet phrase for participation",
    severity: "high",
    reports: 3567,
    lastReported: "6 hours ago",
  },
  {
    url: "https://pi628tokens.com/claim",
    type: "Fake Airdrop",
    description: "Fraudulent 628 token airdrop stealing credentials",
    severity: "high",
    reports: 4234,
    lastReported: "5 hours ago",
  },
  {
    url: "https://claim500picoin.com/home/wallet.php",
    type: "Fake Claim Portal",
    description: "Phishing site claiming 500 Pi distribution, steals credentials",
    severity: "critical",
    reports: 5432,
    lastReported: "2 hours ago",
  },
  {
    url: "https://www.pinetwork-browsers.com/6thpi",
    type: "Fake Browser",
    description: "Fake Pi browser download with malware",
    severity: "critical",
    reports: 4876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://tradep2ppinetwork.com/public/unlock",
    type: "Fake P2P Market",
    description: "Fraudulent P2P trading platform stealing wallet access",
    severity: "high",
    reports: 4123,
    lastReported: "4 hours ago",
  },
  {
    url: "https://peerpaypinet.com/public/unlock",
    type: "Fake P2P Market",
    description: "Fake peer payment platform harvesting credentials",
    severity: "high",
    reports: 3876,
    lastReported: "5 hours ago",
  },
  {
    url: "https://www.pinetwork-event.com/birthday",
    type: "Fake Event",
    description: "Fraudulent birthday event phishing for wallet data",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://pionergift.com/9-2/",
    type: "Giveaway Scam",
    description: "Fake pioneer gift promotion stealing credentials",
    severity: "high",
    reports: 3678,
    lastReported: "5 hours ago",
  },
  {
    url: "https://www.pinetwork-browsers.com/birthdayquy",
    type: "Fake Browser",
    description: "Fake browser birthday event with malware",
    severity: "high",
    reports: 3234,
    lastReported: "6 hours ago",
  },
  {
    url: "https://www.wallet-pinnetwork.com/wallet2",
    type: "Phony Wallet",
    description: "Typosquatted wallet domain stealing credentials",
    severity: "critical",
    reports: 5123,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pionermarket.com/9-2/",
    type: "Fake P2P Market",
    description: "Fake pioneer market stealing wallet access",
    severity: "high",
    reports: 3876,
    lastReported: "5 hours ago",
  },
  {
    url: "https://pi-airdrop.network/wallet2.html",
    type: "Fake Airdrop",
    description: "Phishing airdrop site harvesting wallet credentials",
    severity: "critical",
    reports: 5432,
    lastReported: "2 hours ago",
  },
  {
    url: "https://picore1.com/wallet.html",
    type: "Phony Wallet",
    description: "Fake Pi Core wallet impersonation",
    severity: "critical",
    reports: 4987,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.pinetwork-browsers.com/",
    type: "Typosquatting",
    description: "Misspelled Pi Network browser phishing site",
    severity: "high",
    reports: 3987,
    lastReported: "4 hours ago",
  },
  {
    url: "http://giftwork2025.com/",
    type: "Giveaway Scam",
    description: "Fake 2025 gift promotion phishing for credentials",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://pi-net.work/",
    type: "Typosquatting",
    description: "Typosquatted Pi Network domain phishing site",
    severity: "high",
    reports: 4567,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.facebook.com/share/r/1BT2gHS9xD/",
    type: "Social Media Scam",
    description: "Facebook redirect to phishing sites",
    severity: "medium",
    reports: 2876,
    lastReported: "8 hours ago",
  },
  {
    url: "https://share.google/BQtgoOStA9HE3CQfF",
    type: "Redirect Scam",
    description: "Malicious Google redirect to phishing sites",
    severity: "medium",
    reports: 2456,
    lastReported: "7 hours ago",
  },
  {
    url: "https://clequa.com/clequaBK/",
    type: "Phishing Site",
    description: "Deceptive domain phishing for Pi credentials",
    severity: "high",
    reports: 3234,
    lastReported: "6 hours ago",
  },
  {
    url: "https://clequa.com/",
    type: "Phishing Site",
    description: "Main phishing domain targeting Pi users",
    severity: "high",
    reports: 3234,
    lastReported: "6 hours ago",
  },
  {
    url: "https://unlockpinet.online/wallet.html",
    type: "Phishing Site",
    description: "Fake wallet unlock service harvesting credentials",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://unlockpinet.online/",
    type: "Phishing Site",
    description: "Main domain for wallet unlock phishing",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://piearn.net/",
    type: "Fake Earning Platform",
    description: "Fraudulent earning platform promising Pi rewards for credential sharing",
    severity: "high",
    reports: 3876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://pistoreshop.com/wallet/",
    type: "Fake Store",
    description: "Fake Pi store with wallet phishing functionality",
    severity: "high",
    reports: 4123,
    lastReported: "4 hours ago",
  },
  {
    url: "https://www.facebook.com/share/v/1Ai6hYVxE9/",
    type: "Social Media Scam",
    description: "Facebook redirect link to Pi Network phishing sites",
    severity: "medium",
    reports: 2876,
    lastReported: "5 hours ago",
  },
  {
    url: "http://unlockpi.fwh.is/",
    type: "Phishing Site",
    description: "Fake wallet unlock service stealing recovery phrases",
    severity: "critical",
    reports: 5432,
    lastReported: "1 hour ago",
  },
  {
    url: "https://unlockpi.site/wallet.html",
    type: "Phishing Site",
    description: "Wallet unlock phishing page harvesting passphrases",
    severity: "critical",
    reports: 5678,
    lastReported: "2 hours ago",
  },
  {
    url: "https://www.facebook.com/share/p/14s3hgLVE2/",
    type: "Social Media Scam",
    description: "Facebook share link redirecting to Pi phishing sites",
    severity: "medium",
    reports: 2654,
    lastReported: "6 hours ago",
  },
  {
    url: "https://pi628airdrop.com/wallet",
    type: "Fake Airdrop",
    description: "Fraudulent 628 Pi token airdrop harvesting 24-word recovery phrases",
    severity: "critical",
    reports: 7456,
    lastReported: "10 minutes ago",
  },
  {
    url: "https://pi62tokens.net/claim",
    type: "Fake Airdrop",
    description: "Fake 62 Pi token airdrop phishing for wallet credentials",
    severity: "critical",
    reports: 5432,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pi-wallet-portal-claim.com",
    type: "Phony Wallet",
    description: "Fake Pi Wallet portal from Pi2Day campaign stealing recovery phrases",
    severity: "critical",
    reports: 6987,
    lastReported: "25 minutes ago",
  },
  {
    url: "https://minepi-download.com/app",
    type: "Fake App",
    description: "Malicious Pi mining app download site distributing malware",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pi-mining-software.net",
    type: "Fake Mining App",
    description: "Fake free mining software delivering credential theft malware",
    severity: "critical",
    reports: 5234,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pinetwork-official-app.com",
    type: "Fake App",
    description: "Impersonates official Pi app with malware-infected download",
    severity: "critical",
    reports: 6543,
    lastReported: "30 minutes ago",
  },
  {
    url: "https://pi-network-airdrop.com",
    type: "Fake Airdrop",
    description: "Fake airdrop site promising free Pi tokens to steal wallet credentials",
    severity: "critical",
    reports: 8921,
    lastReported: "15 minutes ago",
  },
  {
    url: "https://pi-claim.net",
    type: "Fake Airdrop",
    description: "Fraudulent Pi token claim site harvesting recovery phrases",
    severity: "critical",
    reports: 7543,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pi-kyc-verify.com",
    type: "Phishing Site",
    description: "Fake KYC verification site stealing personal information and wallet access",
    severity: "critical",
    reports: 9234,
    lastReported: "25 minutes ago",
  },
  {
    url: "https://minepi-airdrop.com",
    type: "Fake Airdrop",
    description: "Impersonates official Pi Network to steal wallet passphrases",
    severity: "critical",
    reports: 6789,
    lastReported: "45 minutes ago",
  },
  {
    url: "https://pi-wallet-verify.net",
    type: "Phishing Site",
    description: "Fake wallet verification site requesting 24-word recovery phrases",
    severity: "critical",
    reports: 8456,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://pi-giveaway.org",
    type: "Fake Airdrop",
    description: "Fraudulent giveaway site promising Pi tokens for wallet credentials",
    severity: "critical",
    reports: 5678,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pi2day-airdrop.com",
    type: "Fake Airdrop",
    description: "Fake Pi2Day celebration airdrop stealing wallet access",
    severity: "critical",
    reports: 7890,
    lastReported: "35 minutes ago",
  },
  {
    url: "https://pi-mainnet-unlock.com",
    type: "Phishing Site",
    description: "Fake mainnet unlock service harvesting wallet credentials",
    severity: "critical",
    reports: 9012,
    lastReported: "10 minutes ago",
  },
  {
    url: "https://pi-token-claim.net",
    type: "Fake Airdrop",
    description: "Fraudulent token claim site requesting recovery phrases",
    severity: "critical",
    reports: 6345,
    lastReported: "1 hour ago",
  },
  {
    url: "https://verify-pi-wallet.com",
    type: "Phishing Site",
    description: "Fake wallet verification requesting sensitive credentials",
    severity: "critical",
    reports: 7123,
    lastReported: "40 minutes ago",
  },
  {
    url: "https://pi-network-kyc.org",
    type: "Phishing Site",
    description: "Fake KYC site stealing government IDs and wallet information",
    severity: "critical",
    reports: 8234,
    lastReported: "30 minutes ago",
  },
  {
    url: "https://free-pi-tokens.com",
    type: "Fake Airdrop",
    description: "Fraudulent free token offer harvesting wallet passphrases",
    severity: "critical",
    reports: 5890,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pi-migration.net",
    type: "Phishing Site",
    description: "Fake migration service stealing wallet recovery phrases",
    severity: "critical",
    reports: 7456,
    lastReported: "50 minutes ago",
  },
  {
    url: "https://pinetwork-verify.com",
    type: "Phishing Site",
    description: "Impersonates official Pi Network for credential theft",
    severity: "critical",
    reports: 8901,
    lastReported: "15 minutes ago",
  },
  {
    url: "https://claim-pi-airdrop.org",
    type: "Fake Airdrop",
    description: "Fake airdrop claiming 62-628 Pi tokens to steal wallet access",
    severity: "critical",
    reports: 9345,
    lastReported: "5 minutes ago",
  },
  {
    url: "http://unlockpi.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "https://unlockpi.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "https://unlockpi.org/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "http://unlockpi.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "https://confpiwallet.web.app/login.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet login page hosted on Firebase that steals credentials and recovery phrases",
    reports: 3421,
    lastReported: "2025-02-03",
  },
  {
    url: "https://confpiwallet.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet login page hosted on Firebase that steals credentials and recovery phrases",
    reports: 3421,
    lastReported: "2025-02-03",
  },
  {
    url: "confpiwallet.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet login page hosted on Firebase that steals credentials and recovery phrases",
    reports: 3421,
    lastReported: "2025-02-03",
  },
  {
    url: "https://pi-onlineshop.net/wallet.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi online shop that redirects to wallet phishing page to steal credentials",
    reports: 2876,
    lastReported: "2025-02-03",
  },
  {
    url: "https://pi-onlineshop.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi online shop that redirects to wallet phishing page to steal credentials",
    reports: 2876,
    lastReported: "2025-02-03",
  },
  {
    url: "pi-onlineshop.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi online shop that redirects to wallet phishing page to steal credentials",
    reports: 2876,
    lastReported: "2025-02-03",
  },
  {
    url: "http://pinet7.com/wallet.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network wallet page that harvests user credentials and recovery phrases",
    reports: 4512,
    lastReported: "2025-02-03",
  },
  {
    url: "https://pinet7.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network wallet page that harvests user credentials and recovery phrases",
    reports: 4512,
    lastReported: "2025-02-03",
  },
  {
    url: "pinet7.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network wallet page that harvests user credentials and recovery phrases",
    reports: 4512,
    lastReported: "2025-02-03",
  },
  {
    url: "https://airdropnet2025.com/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop site promising free Pi tokens in exchange for wallet credentials",
    reports: 5234,
    lastReported: "2025-02-03",
  },
  {
    url: "https://airdropnet2025.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop site promising free Pi tokens in exchange for wallet credentials",
    reports: 5234,
    lastReported: "2025-02-03",
  },
  {
    url: "airdropnet2025.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop site promising free Pi tokens in exchange for wallet credentials",
    reports: 5234,
    lastReported: "2025-02-03",
  },
  {
    url: "https://2pidays.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 8942,
    lastReported: "2025-06-15",
  },
  {
    url: "https://2pidays.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 8942,
    lastReported: "2025-06-15",
  },
  {
    url: "2pidays.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 8942,
    lastReported: "2025-06-15",
  },
  {
    url: "https://2pidays.us/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 7856,
    lastReported: "2025-06-15",
  },
  {
    url: "https://2pidays.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 7856,
    lastReported: "2025-06-15",
  },
  {
    url: "2pidays.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 7856,
    lastReported: "2025-06-15",
  },

  {
    url: "https://pinte.help/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating pinet.help to steal Pi wallet credentials",
    reports: 4523,
    lastReported: "2025-06-10",
  },
  {
    url: "https://pinte.help",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating pinet.help to steal Pi wallet credentials",
    severity: "critical",
    reports: 4523,
    lastReported: "2025-06-10",
  },
  {
    url: "pinte.help",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating pinet.help to steal Pi wallet credentials",
    reports: 4523,
    lastReported: "2025-06-10",
  },
  {
    url: "https://wallet-pi.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site mimicking official wallet.pi.net to steal passphrases",
    reports: 6234,
    lastReported: "2025-06-12",
  },
  {
    url: "https://wallet-pi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site mimicking official wallet.pi.net to steal passphrases",
    reports: 6234,
    lastReported: "2025-06-12",
  },
  {
    url: "wallet-pi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site mimicking official wallet.pi.net to steal passphrases",
    reports: 6234,
    lastReported: "2025-06-12",
  },
  {
    url: "https://pi-wallet.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site designed to harvest 24-word recovery phrases",
    reports: 5892,
    lastReported: "2025-06-11",
  },
  {
    url: "https://pi-wallet.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site designed to harvest 24-word recovery phrases",
    reports: 5892,
    lastReported: "2025-06-11",
  },
  {
    url: "pi-wallet.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site designed to harvest 24-word recovery phrases",
    reports: 5892,
    lastReported: "2025-06-11",
  },
  {
    url: "https://mine-pi.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating official minepi.com to steal credentials",
    reports: 5123,
    lastReported: "2025-06-09",
  },
  {
    url: "https://mine-pi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating official minepi.com to steal credentials",
    reports: 5123,
    lastReported: "2025-06-09",
  },
  {
    url: "mine-pi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating official minepi.com to steal credentials",
    reports: 5123,
    lastReported: "2025-06-09",
  },
  {
    url: "https://minepl.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepl instead of minepi) to steal Pi credentials",
    reports: 3421,
    lastReported: "2025-06-15",
  },
  {
    url: "minepl.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepl instead of minepi) to steal Pi credentials",
    reports: 3421,
    lastReported: "2025-06-15",
  },
  {
    url: "https://minepj.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepj instead of minepi) to steal Pi credentials",
    reports: 2876,
    lastReported: "2025-06-14",
  },
  {
    url: "minepj.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepj instead of minepi) to steal Pi credentials",
    reports: 2876,
    lastReported: "2025-06-14",
  },
  {
    url: "https://minepi.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Domain using .net instead of .com to impersonate official Pi Network site",
    reports: 4532,
    lastReported: "2025-06-16",
  },
  {
    url: "minepi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Domain using .net instead of .com to impersonate official Pi Network site",
    reports: 4532,
    lastReported: "2025-06-16",
  },
  {
    url: "https://pi-network.org/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake official-sounding Pi Network domain used for phishing",
    reports: 5234,
    lastReported: "2025-06-17",
  },
  {
    url: "pi-network.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake official-sounding Pi Network domain used for phishing",
    reports: 5234,
    lastReported: "2025-06-17",
  },
  {
    url: "https://pinetwork.app/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network app domain used to distribute malicious apps",
    reports: 3987,
    lastReported: "2025-06-18",
  },
  {
    url: "pinetwork.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network app domain used to distribute malicious apps",
    reports: 3987,
    lastReported: "2025-06-18",
  },
  {
    url: "https://wallet.pinetwork.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain impersonating official Pi wallet to steal passphrases",
    reports: 6543,
    lastReported: "2025-06-19",
  },
  {
    url: "wallet.pinetwork.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain impersonating official Pi wallet to steal passphrases",
    reports: 6543,
    lastReported: "2025-06-19",
  },
  {
    url: "https://pi-wallet.app/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet app domain for stealing wallet credentials",
    reports: 4123,
    lastReported: "2025-06-20",
  },
  {
    url: "pi-wallet.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet app domain for stealing wallet credentials",
    reports: 4123,
    lastReported: "2025-06-20",
  },
  {
    url: "https://claim-pi.com/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake airdrop site promising free Pi tokens in exchange for wallet access",
    reports: 7234,
    lastReported: "2025-06-21",
  },
  {
    url: "claim-pi.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake airdrop site promising free Pi tokens in exchange for wallet access",
    reports: 7234,
    lastReported: "2025-06-21",
  },
  {
    url: "https://free-pi.net/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Scam site offering free Pi tokens to harvest wallet passphrases",
    reports: 5876,
    lastReported: "2025-06-22",
  },
  {
    url: "free-pi.net",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Scam site offering free Pi tokens to harvest wallet passphrases",
    reports: 5876,
    lastReported: "2025-06-22",
  },
  {
    url: "https://pi-claim.org/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop claiming site that steals recovery phrases",
    reports: 4987,
    lastReported: "2025-06-23",
  },
  {
    url: "pi-claim.org",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop claiming site that steals recovery phrases",
    reports: 4987,
    lastReported: "2025-06-23",
  },

  // New cryptocurrency scam domains reported in May 2025
  {
    url: "https://swapbase.finance/",
    type: "Crypto Drainer",
    severity: "critical",
    description: "Fake SwapBased website - crypto drainer that steals funds through malicious smart contracts",
    reports: 6234,
    lastReported: "2025-05-18",
  },
  {
    url: "swapbase.finance",
    type: "Crypto Drainer",
    severity: "critical",
    description: "Fake SwapBased website - crypto drainer that steals funds through malicious smart contracts",
    reports: 6234,
    lastReported: "2025-05-18",
  },
  {
    url: "https://medaigenesis.cc/",
    type: "Wallet Theft",
    severity: "critical",
    description: "Cryptocurrency wallet phishing site coordinated with other scam domains",
    reports: 5892,
    lastReported: "2025-05-22",
  },
  {
    url: "medaigenesis.cc",
    type: "Wallet Theft",
    severity: "critical",
    description: "Cryptocurrency wallet phishing site coordinated with other scam domains",
    reports: 5892,
    lastReported: "2025-05-22",
  },
  {
    url: "https://novacrypt.net/",
    type: "Wallet Theft",
    severity: "critical",
    description: "Cryptocurrency wallet phishing site part of coordinated scam infrastructure",
    reports: 5743,
    lastReported: "2025-05-21",
  },
  {
    url: "novacrypt.net",
    type: "Wallet Theft",
    severity: "critical",
    description: "Cryptocurrency wallet phishing site part of coordinated scam infrastructure",
    reports: 5743,
    lastReported: "2025-05-21",
  },
  {
    url: "https://zzztd.com/",
    type: "Wallet Theft",
    severity: "critical",
    description: "Cryptocurrency wallet phishing site with shared scam server infrastructure",
    reports: 5621,
    lastReported: "2025-05-20",
  },
  {
    url: "zzztd.com",
    type: "Wallet Theft",
    severity: "critical",
    description: "Cryptocurrency wallet phishing site with shared scam server infrastructure",
    reports: 5621,
    lastReported: "2025-05-20",
  },
  {
    url: "https://setup.trozre.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Trezor hardware wallet setup page designed to steal recovery seeds",
    reports: 7845,
    lastReported: "2025-05-25",
  },
  {
    url: "setup.trozre.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Trezor hardware wallet setup page designed to steal recovery seeds",
    reports: 7845,
    lastReported: "2025-05-25",
  },
  {
    url: "https://trozre.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain mimicking Trezor (trozre instead of trezor)",
    reports: 7845,
    lastReported: "2025-05-25",
  },
  {
    url: "trozre.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain mimicking Trezor (trozre instead of trezor)",
    reports: 7845,
    lastReported: "2025-05-25",
  },
  {
    url: "https://dichuyenpinet.com/verify.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network verification site stealing wallet credentials",
    reports: 3421,
    lastReported: "2025-05-28",
  },
  {
    url: "dichuyenpinet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network verification site stealing wallet credentials",
    reports: 3421,
    lastReported: "2025-05-28",
  },
  {
    url: "https://piwallettools.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet tools site designed to steal passphrases",
    reports: 5678,
    lastReported: "2025-05-29",
  },
  {
    url: "piwallettools.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet tools site designed to steal passphrases",
    reports: 5678,
    lastReported: "2025-05-29",
  },
  {
    url: "https://p2p.walletpinet.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi P2P trading platform phishing for wallet access",
    reports: 4892,
    lastReported: "2025-05-29",
  },
  {
    url: "p2p.walletpinet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi P2P trading platform phishing for wallet access",
    reports: 4892,
    lastReported: "2025-05-29",
  },
  {
    url: "https://pi-add.com/wallet",
    type: "Phishing Site",
    severity: "critical",
    description: "Fraudulent site claiming to add Pi tokens to wallets",
    reports: 2956,
    lastReported: "2025-05-28",
  },
  {
    url: "pi-add.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fraudulent site claiming to add Pi tokens to wallets",
    reports: 2956,
    lastReported: "2025-05-28",
  },
  {
    url: "https://piwalletapp.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet application download site with malware",
    reports: 6234,
    lastReported: "2025-05-29",
  },
  {
    url: "piwalletapp.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet application download site with malware",
    reports: 6234,
    lastReported: "2025-05-29",
  },
  {
    url: "https://pinetservice.site/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network service portal stealing user credentials",
    reports: 3845,
    lastReported: "2025-05-28",
  },
  {
    url: "pinetservice.site",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network service portal stealing user credentials",
    reports: 3845,
    lastReported: "2025-05-28",
  },
  {
    url: "https://chengdiao.fun/",
    type: "Scam Site",
    severity: "critical",
    description: "Suspicious Chinese domain linked to Pi Network scams",
    reports: 2147,
    lastReported: "2025-05-27",
  },
  {
    url: "chengdiao.fun",
    type: "Scam Site",
    severity: "critical",
    description: "Suspicious Chinese domain linked to Pi Network scams",
    reports: 2147,
    lastReported: "2025-05-27",
  },
  {
    url: "https://piexchange.sbs/wallet/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi exchange platform stealing wallet passphrases",
    reports: 5423,
    lastReported: "2025-05-29",
  },
  {
    url: "piexchange.sbs",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi exchange platform stealing wallet passphrases",
    reports: 5423,
    lastReported: "2025-05-29",
  },
  {
    url: "https://minepihub.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi mining hub offering fraudulent mining services",
    reports: 4567,
    lastReported: "2025-05-28",
  },
  {
    url: "minepihub.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi mining hub offering fraudulent mining services",
    reports: 4567,
    lastReported: "2025-05-28",
  },
  {
    url: "https://pi-mainnet.shop/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi mainnet shop selling non-existent Pi tokens",
    reports: 3912,
    lastReported: "2025-05-29",
  },
  {
    url: "pi-mainnet.shop",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi mainnet shop selling non-existent Pi tokens",
    reports: 3912,
    lastReported: "2025-05-29",
  },
  {
    url: "https://tracuupinet.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network lookup service stealing user data",
    reports: 2834,
    lastReported: "2025-05-28",
  },
  {
    url: "tracuupinet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network lookup service stealing user data",
    reports: 2834,
    lastReported: "2025-05-28",
  },
  {
    url: "https://unlocktestnet.com/verify.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake testnet unlock verification page stealing credentials",
    reports: 4156,
    lastReported: "2025-05-29",
  },
  {
    url: "unlocktestnet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake testnet unlock verification page stealing credentials",
    reports: 4156,
    lastReported: "2025-05-29",
  },
  {
    url: "https://pinetdrop.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network airdrop site stealing wallet credentials",
    reports: 3842,
    lastReported: "2025-06-02",
  },
  {
    url: "https://pinetdrop.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network airdrop site stealing wallet credentials",
    reports: 3842,
    lastReported: "2025-06-02",
  },
  {
    url: "pinetdrop.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network airdrop site stealing wallet credentials",
    reports: 3842,
    lastReported: "2025-06-02",
  },
  {
    url: "https://2fapicore.com/wallet/index.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake 2FA Pi Core wallet verification page stealing passphrases",
    reports: 5217,
    lastReported: "2025-06-03",
  },
  {
    url: "https://2fapicore.com/wallet/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake 2FA Pi Core wallet verification page stealing passphrases",
    reports: 5217,
    lastReported: "2025-06-03",
  },
  {
    url: "https://2fapicore.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake 2FA Pi Core wallet verification page stealing passphrases",
    reports: 5217,
    lastReported: "2025-06-03",
  },
  {
    url: "2fapicore.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake 2FA Pi Core wallet verification page stealing passphrases",
    reports: 5217,
    lastReported: "2025-06-03",
  },
  {
    url: "https://pi-alo.com/wallet",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet page targeting user credentials and passphrases",
    reports: 4892,
    lastReported: "2025-06-04",
  },
  {
    url: "https://pi-alo.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet page targeting user credentials and passphrases",
    reports: 4892,
    lastReported: "2025-06-04",
  },
  {
    url: "pi-alo.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet page targeting user credentials and passphrases",
    reports: 4892,
    lastReported: "2025-06-04",
  },
  // </CHANGE> Adding June 2025 reported scam domains and typosquatting variants
  {
    url: "wallet.pi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain - Official is wallet.pinet.com only",
    reports: 8923,
    lastReported: "2025-06-05",
  },
  {
    url: "https://wallet.pi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain - Official is wallet.pinet.com only",
    reports: 8923,
    lastReported: "2025-06-05",
  },
  {
    url: "wallet-pi.net",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant of official wallet domain",
    reports: 6847,
    lastReported: "2025-06-05",
  },
  {
    url: "https://wallet-pi.net",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant of official wallet domain",
    reports: 6847,
    lastReported: "2025-06-05",
  },
  {
    url: "walletpi.net",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant removing dots from official domain",
    reports: 5932,
    lastReported: "2025-06-05",
  },
  {
    url: "https://walletpi.net",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant removing dots from official domain",
    reports: 5932,
    lastReported: "2025-06-05",
  },
  {
    url: "wallet.plnet.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Uses 'pl' instead of 'pi' to confuse users",
    reports: 4521,
    lastReported: "2025-06-04",
  },
  {
    url: "https://wallet.plnet.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Uses 'pl' instead of 'pi' to confuse users",
    reports: 4521,
    lastReported: "2025-06-04",
  },
  {
    url: "wallet.pinet.net",
    type: "Typosquatting",
    severity: "critical",
    description: "Uses .net instead of .com TLD",
    reports: 7234,
    lastReported: "2025-06-05",
  },
  {
    url: "https://wallet.pinet.net",
    type: "Typosquatting",
    severity: "critical",
    description: "Uses .net instead of .com TLD",
    reports: 7234,
    lastReported: "2025-06-05",
  },
  {
    url: "wallet.pinet.org",
    type: "Typosquatting",
    severity: "critical",
    description: "Uses .org instead of .com TLD",
    reports: 6128,
    lastReported: "2025-06-04",
  },
  {
    url: "https://wallet.pinet.org",
    type: "Typosquatting",
    severity: "critical",
    description: "Uses .org instead of .com TLD",
    reports: 6128,
    lastReported: "2025-06-04",
  },
  {
    url: "pi-network-wallet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain with expanded name to appear official",
    reports: 5643,
    lastReported: "2025-06-03",
  },
  {
    url: "https://pi-network-wallet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain with expanded name to appear official",
    reports: 5643,
    lastReported: "2025-06-03",
  },
  {
    url: "pinetwork-wallet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain impersonating official brand",
    reports: 5321,
    lastReported: "2025-06-03",
  },
  {
    url: "https://pinetwork-wallet.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain impersonating official brand",
    reports: 5321,
    lastReported: "2025-06-03",
  },
  // </CHANGE> Adding June 2025 reported scam domains and typosquatting variants
  {
    url: "https://piopened.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi opened network site",
    reports: 3245,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piopened.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi opened network site",
    reports: 3245,
    lastReported: "2026-01-06",
  },
  {
    url: "https://dapps-portal.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake dApps portal",
    reports: 4521,
    lastReported: "2026-01-06",
  },
  {
    url: "http://dapps-portal.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake dApps portal",
    reports: 4521,
    lastReported: "2026-01-06",
  },
  {
    url: "https://p2pppinetwork.click",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake P2P Pi network",
    reports: 2876,
    lastReported: "2026-01-06",
  },
  {
    url: "http://p2pppinetwork.click",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake P2P Pi network",
    reports: 2876,
    lastReported: "2026-01-06",
  },
  {
    url: "https://openpi.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake open Pi network",
    reports: 3654,
    lastReported: "2026-01-06",
  },
  {
    url: "http://openpi.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake open Pi network",
    reports: 3654,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pimineapp.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi mining app",
    reports: 5123,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pimineapp.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi mining app",
    reports: 5123,
    lastReported: "2026-01-06",
  },
  {
    url: "https://bonuspi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake bonus Pi offer",
    reports: 4892,
    lastReported: "2026-01-06",
  },
  {
    url: "http://bonuspi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake bonus Pi offer",
    reports: 4892,
    lastReported: "2026-01-06",
  },
  {
    url: "https://bonuspi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake bonus Pi offer",
    reports: 4765,
    lastReported: "2026-01-06",
  },
  {
    url: "http://bonuspi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake bonus Pi offer",
    reports: 4765,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pi6th.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi anniversary/event site",
    reports: 3421,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pi6th.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi anniversary/event site",
    reports: 3421,
    lastReported: "2026-01-06",
  },
  {
    url: "https://piblockchain.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake blockchain site",
    reports: 4123,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piblockchain.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake blockchain site",
    reports: 4123,
    lastReported: "2026-01-06",
  },
  {
    url: "https://piopen.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi open network",
    reports: 3987,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piopen.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi open network",
    reports: 3987,
    lastReported: "2026-01-06",
  },
  {
    url: "https://piunlocked.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi unlock site",
    reports: 4567,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piunlocked.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi unlock site",
    reports: 4567,
    lastReported: "2026-01-06",
  },
  {
    url: "https://piearn.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi earning scheme",
    reports: 3214,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piearn.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi earning scheme",
    reports: 3214,
    lastReported: "2026-01-06",
  },
  {
    url: "https://piminex.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi mining exchange",
    reports: 4876,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piminex.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi mining exchange",
    reports: 4876,
    lastReported: "2026-01-06",
  },
  {
    url: "https://minepinetworkusa.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake USA Pi mining site on Firebase",
    reports: 5234,
    lastReported: "2026-01-06",
  },
  {
    url: "http://minepinetworkusa.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake USA Pi mining site on Firebase",
    reports: 5234,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pifounders.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake founders program",
    reports: 3765,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pifounders.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake founders program",
    reports: 3765,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinetworkauth.onrender.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi auth site on Render",
    reports: 4321,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinetworkauth.onrender.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi auth site on Render",
    reports: 4321,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinetzone.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi zone portal",
    reports: 2987,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinetzone.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi zone portal",
    reports: 2987,
    lastReported: "2026-01-06",
  },
  {
    url: "https://crowdfundpi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake crowdfunding scheme",
    reports: 3456,
    lastReported: "2026-01-06",
  },
  {
    url: "http://crowdfundpi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake crowdfunding scheme",
    reports: 3456,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinet-id.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi ID verification",
    reports: 4654,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinet-id.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi ID verification",
    reports: 4654,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinetusa.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake USA Pi site on Firebase",
    reports: 3876,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinetusa.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake USA Pi site on Firebase",
    reports: 3876,
    lastReported: "2026-01-06",
  },
  {
    url: "https://claim-pinettworks.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake claim Pi rewards",
    reports: 5123,
    lastReported: "2026-01-06",
  },
  {
    url: "http://claim-pinettworks.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake claim Pi rewards",
    reports: 5123,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pi-unlocking.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi unlocking service",
    reports: 4234,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pi-unlocking.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi unlocking service",
    reports: 4234,
    lastReported: "2026-01-06",
  },
  {
    url: "https://paymentrecieveoptions.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake payment portal",
    reports: 2765,
    lastReported: "2026-01-06",
  },
  {
    url: "http://paymentrecieveoptions.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake payment portal",
    reports: 2765,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinetworkupdater.site",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi Network updater",
    reports: 3987,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinetworkupdater.site",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake Pi Network updater",
    reports: 3987,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinosnetwork.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Official Pi Network scam list - typosquatting of Pi Network",
    reports: 4321,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinosnetwork.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Official Pi Network scam list - typosquatting of Pi Network",
    reports: 4321,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinethelp.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Official Pi Network scam list - fake help/support site mimicking pinet.help",
    reports: 5234,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinethelp.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Official Pi Network scam list - fake help/support site mimicking pinet.help",
    reports: 5234,
    lastReported: "2026-01-06",
  },
  {
    url: "https://piwalletdrop.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake wallet airdrop",
    reports: 4567,
    lastReported: "2026-01-06",
  },
  {
    url: "http://piwalletdrop.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake wallet airdrop",
    reports: 4567,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pay.optionalhub.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake payment hub",
    reports: 2876,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pay.optionalhub.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Official Pi Network scam list - fake payment hub",
    reports: 2876,
    lastReported: "2026-01-06",
  },
  {
    url: "https://pinetpi.org",
    type: "Typosquatting",
    severity: "critical",
    description: "Official Pi Network scam list - typosquatting of pinet domains",
    reports: 3654,
    lastReported: "2026-01-06",
  },
  {
    url: "http://pinetpi.org",
    type: "Typosquatting",
    severity: "critical",
    description: "Official Pi Network scam list - typosquatting of pinet domains",
    reports: 3654,
    lastReported: "2026-01-06",
  },
  // </CHANGE> Adding January 2026 reported scam domains
  {
    url: "https://www.pinetwork0.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant using '0' instead of 'o' in pinetwork",
    reports: 125,
    lastReported: "2026-01-12",
  },
  {
    url: "http://www.pinetwork0.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant using '0' instead of 'o' in pinetwork",
    reports: 125,
    lastReported: "2026-01-12",
  },
  {
    url: "https://pinetwork0.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant using '0' instead of 'o' in pinetwork",
    reports: 125,
    lastReported: "2026-01-12",
  },
  {
    url: "http://pinetwork0.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant using '0' instead of 'o' in pinetwork",
    reports: 125,
    lastReported: "2026-01-12",
  },
  // </CHANGE> Adding pinetwork0.com typosquatting variant
  {
    url: "https://pinethelp.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi help site impersonating official pinet.help domain",
    reports: 847,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pinethelp.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi help site impersonating official pinet.help domain",
    reports: 847,
    lastReported: "2026-01-13",
  },
  {
    url: "https://piwalletdrop.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent wallet drop claiming free Pi tokens",
    reports: 923,
    lastReported: "2026-01-13",
  },
  {
    url: "http://piwalletdrop.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent wallet drop claiming free Pi tokens",
    reports: 923,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pay.optionalhub.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake payment options hub stealing wallet credentials",
    reports: 412,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pay.optionalhub.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake payment options hub stealing wallet credentials",
    reports: 412,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pinetpi.org",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting of official Pi Network domain",
    reports: 561,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pinetpi.org",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting of official Pi Network domain",
    reports: 561,
    lastReported: "2026-01-13",
  },
  {
    url: "https://paymentrecieveoptions.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake payment receive options stealing Pi credentials",
    reports: 389,
    lastReported: "2026-01-13",
  },
  {
    url: "http://paymentrecieveoptions.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake payment receive options stealing Pi credentials",
    reports: 389,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pinosnetwork.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant of Pi Network domain",
    reports: 634,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pinosnetwork.com",
    type: "Typosquatting",
    severity: "critical",
    description: "Typosquatting variant of Pi Network domain",
    reports: 634,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pinetworkupdater.site",
    type: "Fake App",
    severity: "critical",
    description: "Fake updater site distributing malware disguised as Pi app update",
    reports: 754,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pinetworkupdater.site",
    type: "Fake App",
    severity: "critical",
    description: "Fake updater site distributing malware disguised as Pi app update",
    reports: 754,
    lastReported: "2026-01-13",
  },
  {
    url: "https://claim-pinettworks.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake claim site for Pi Network tokens",
    reports: 492,
    lastReported: "2026-01-13",
  },
  {
    url: "http://claim-pinettworks.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake claim site for Pi Network tokens",
    reports: 492,
    lastReported: "2026-01-13",
  },
  {
    url: "https://crowdfundpi.com",
    type: "Scam",
    severity: "critical",
    description: "Fraudulent crowdfunding scheme claiming Pi backing",
    reports: 318,
    lastReported: "2026-01-13",
  },
  {
    url: "http://crowdfundpi.com",
    type: "Scam",
    severity: "critical",
    description: "Fraudulent crowdfunding scheme claiming Pi backing",
    reports: 318,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pinet-id.com",
    type: "Fake KYC",
    severity: "critical",
    description: "Fake KYC verification site stealing identity documents",
    reports: 876,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pinet-id.com",
    type: "Fake KYC",
    severity: "critical",
    description: "Fake KYC verification site stealing identity documents",
    reports: 876,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pinetzone.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network zone site harvesting credentials",
    reports: 529,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pinetzone.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network zone site harvesting credentials",
    reports: 529,
    lastReported: "2026-01-13",
  },
  {
    url: "https://pifounders.com",
    type: "Impersonation",
    severity: "critical",
    description: "Fake site impersonating Pi Network founders",
    reports: 691,
    lastReported: "2026-01-13",
  },
  {
    url: "http://pifounders.com",
    type: "Impersonation",
    severity: "critical",
    description: "Fake site impersonating Pi Network founders",
    reports: 691,
    lastReported: "2026-01-13",
  },
  {
    url: "https://piminex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi mining exchange platform",
    reports: 445,
    lastReported: "2026-01-13",
  },
  {
    url: "http://piminex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi mining exchange platform",
    reports: 445,
    lastReported: "2026-01-13",
  },
  // <CHANGE> Adding 6 new reported scam sites
  {
    url: "https://pibitgetpay.com/wallet.html",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake wallet claiming Bitget integration to steal credentials",
    reports: 89,
    lastReported: "2026-01-23",
  },
  {
    url: "http://pibitgetpay.com/wallet.html",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake wallet claiming Bitget integration to steal credentials",
    reports: 89,
    lastReported: "2026-01-23",
  },
  {
    url: "https://dichuyennetwork.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Suspicious site impersonating Pi Network with Vietnamese domain",
    reports: 67,
    lastReported: "2026-01-23",
  },
  {
    url: "http://dichuyennetwork.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Suspicious site impersonating Pi Network with Vietnamese domain",
    reports: 67,
    lastReported: "2026-01-23",
  },
  {
    url: "https://pinetwok.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting variant of Pi Network domain",
    reports: 143,
    lastReported: "2026-01-23",
  },
  {
    url: "http://pinetwok.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting variant of Pi Network domain",
    reports: 143,
    lastReported: "2026-01-23",
  },
  {
    url: "https://piminedex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi mining DEX claiming token exchange",
    reports: 201,
    lastReported: "2026-01-23",
  },
  {
    url: "http://piminedex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi mining DEX claiming token exchange",
    reports: 201,
    lastReported: "2026-01-23",
  },
  {
    url: "https://pipayexchange.online/wallet",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi payment exchange wallet stealing credentials",
    reports: 178,
    lastReported: "2026-01-23",
  },
  {
    url: "http://pipayexchange.online/wallet",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi payment exchange wallet stealing credentials",
    reports: 178,
    lastReported: "2026-01-23",
  },
  {
    url: "https://pimallshopitem.web.app",
    type: "Fake Shopping",
    severity: "critical",
    description: "Fraudulent Pi shopping platform hosted on Firebase",
    reports: 92,
    lastReported: "2026-01-23",
  },
  {
    url: "http://pimallshopitem.web.app",
    type: "Fake Shopping",
    severity: "critical",
    description: "Fraudulent Pi shopping platform hosted on Firebase",
    reports: 92,
    lastReported: "2026-01-23",
  },
  // <CHANGE> Adding 2 new reported scam sites
  {
    url: "https://pinetworld.net/wallet",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake wallet page claiming Pi Network world wallet access",
    reports: 156,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pinetworld.net/wallet",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake wallet page claiming Pi Network world wallet access",
    reports: 156,
    lastReported: "2026-01-24",
  },
  {
    url: "https://networkpi.web.app/login.html",
    type: "Phishing Login",
    severity: "critical",
    description: "Phishing login page hosted on Firebase impersonating Pi Network",
    reports: 203,
    lastReported: "2026-01-24",
  },
  {
    url: "http://networkpi.web.app/login.html",
    type: "Phishing Login",
    severity: "critical",
    description: "Phishing login page hosted on Firebase impersonating Pi Network",
    reports: 203,
    lastReported: "2026-01-24",
  },
  // <CHANGE> Adding new domains from official Pi Network scam list (January 2026)
  {
    url: "https://pi-mypage.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network personal page impersonating official platform",
    reports: 267,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pi-mypage.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network personal page impersonating official platform",
    reports: 267,
    lastReported: "2026-01-24",
  },
  {
    url: "https://piteamcore.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Core Team website stealing credentials",
    reports: 312,
    lastReported: "2026-01-24",
  },
  {
    url: "http://piteamcore.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Core Team website stealing credentials",
    reports: 312,
    lastReported: "2026-01-24",
  },
  {
    url: "https://picash.network",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi cash network claiming token exchange",
    reports: 189,
    lastReported: "2026-01-24",
  },
  {
    url: "http://picash.network",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi cash network claiming token exchange",
    reports: 189,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pigiggle.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Suspicious Pi-themed site with unclear purpose",
    reports: 134,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pigiggle.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Suspicious Pi-themed site with unclear purpose",
    reports: 134,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pievent.us",
    type: "Fake Event",
    severity: "critical",
    description: "Fake Pi Network event site collecting user data",
    reports: 178,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pievent.us",
    type: "Fake Event",
    severity: "critical",
    description: "Fake Pi Network event site collecting user data",
    reports: 178,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pinetusa.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Firebase-hosted fake Pi Network USA site",
    reports: 156,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pinetusa.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Firebase-hosted fake Pi Network USA site",
    reports: 156,
    lastReported: "2026-01-24",
  },
  // <CHANGE> Adding user-reported fake wallet
  {
    url: "https://2fapinetwallet.com/wallet/index-vi",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network wallet targeting Vietnamese users with credential theft",
    reports: 98,
    lastReported: "2026-01-24",
  },
  {
    url: "http://2fapinetwallet.com/wallet/index-vi",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network wallet targeting Vietnamese users with credential theft",
    reports: 98,
    lastReported: "2026-01-24",
  },
  // <CHANGE> Adding 11 new reported scam sites
  {
    url: "https://pidex.netlify.app",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi DEX hosted on Netlify claiming token exchange",
    reports: 234,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pidex.netlify.app",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi DEX hosted on Netlify claiming token exchange",
    reports: 234,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pinetwork9.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network variant site with number suffix",
    reports: 187,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pinetwork9.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network variant site with number suffix",
    reports: 187,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pinetdex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network DEX claiming decentralized exchange",
    reports: 312,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pinetdex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network DEX claiming decentralized exchange",
    reports: 312,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pimines.com",
    type: "Fake Mining",
    severity: "critical",
    description: "Fake Pi mining site promising enhanced mining rates",
    reports: 278,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pimines.com",
    type: "Fake Mining",
    severity: "critical",
    description: "Fake Pi mining site promising enhanced mining rates",
    reports: 278,
    lastReported: "2026-01-24",
  },
  {
    url: "https://piworkmove.com/verify.php",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake verification page stealing user credentials via PHP script",
    reports: 156,
    lastReported: "2026-01-24",
  },
  {
    url: "http://piworkmove.com/verify.php",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake verification page stealing user credentials via PHP script",
    reports: 156,
    lastReported: "2026-01-24",
  },
  {
    url: "https://piwebair.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Suspicious Pi-themed domain with unclear malicious purpose",
    reports: 143,
    lastReported: "2026-01-24",
  },
  {
    url: "http://piwebair.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Suspicious Pi-themed domain with unclear malicious purpose",
    reports: 143,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pinetmarket.online/wallet.html",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi marketplace wallet page stealing credentials",
    reports: 289,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pinetmarket.online/wallet.html",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi marketplace wallet page stealing credentials",
    reports: 289,
    lastReported: "2026-01-24",
  },
  {
    url: "https://netpimove.com/verify.html",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake Pi Network verification page collecting user data",
    reports: 198,
    lastReported: "2026-01-24",
  },
  {
    url: "http://netpimove.com/verify.html",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake Pi Network verification page collecting user data",
    reports: 198,
    lastReported: "2026-01-24",
  },
  {
    url: "https://minepiconfirm.web.app/login.html",
    type: "Phishing Login",
    severity: "critical",
    description: "Firebase-hosted fake Pi login confirmation page",
    reports: 267,
    lastReported: "2026-01-24",
  },
  {
    url: "http://minepiconfirm.web.app/login.html",
    type: "Phishing Login",
    severity: "critical",
    description: "Firebase-hosted fake Pi login confirmation page",
    reports: 267,
    lastReported: "2026-01-24",
  },
  {
    url: "https://pinetwork4.com/wallet.html",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network variant wallet with number suffix",
    reports: 221,
    lastReported: "2026-01-24",
  },
  {
    url: "http://pinetwork4.com/wallet.html",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network variant wallet with number suffix",
    reports: 221,
    lastReported: "2026-01-24",
  },
  {
    url: "https://www.facebook.com/share/r/1DXuJHxNWR",
    type: "Social Media Scam",
    severity: "critical",
    description: "Facebook scam post/link promoting fraudulent Pi offers",
    reports: 345,
    lastReported: "2026-01-24",
  },
  // <CHANGE> Adding new reported fake wallet
  {
    url: "https://pinetdrop2026.info/wallet",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network airdrop wallet claiming 2026 token distribution",
    reports: 214,
    lastReported: "2026-02-07",
  },
  {
    url: "http://pinetdrop2026.info/wallet",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network airdrop wallet claiming 2026 token distribution",
    reports: 214,
    lastReported: "2026-02-07",
  },
  // <CHANGE> Adding new reported fake airdrop
  {
    url: "https://piclaimairdrop.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent Pi Network airdrop claim site stealing credentials",
    reports: 187,
    lastReported: "2026-02-11",
  },
  {
    url: "http://piclaimairdrop.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent Pi Network airdrop claim site stealing credentials",
    reports: 187,
    lastReported: "2026-02-11",
  },
  // <CHANGE> Adding Facebook ad-promoted scam
  {
    url: "https://pinetdrop2026.info/get/dual",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Facebook ad-promoted fake Pi airdrop with dual claim scam and tracking parameters",
    reports: 298,
    lastReported: "2026-02-11",
  },
  {
    url: "http://pinetdrop2026.info/get/dual",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Facebook ad-promoted fake Pi airdrop with dual claim scam and tracking parameters",
    reports: 298,
    lastReported: "2026-02-11",
  },
  // <CHANGE> Adding fake Pi selling platform
  {
    url: "https://www.sellpinetwork.cu.ma",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network selling platform claiming to facilitate Pi token sales",
    reports: 163,
    lastReported: "2026-02-11",
  },
  {
    url: "http://www.sellpinetwork.cu.ma",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network selling platform claiming to facilitate Pi token sales",
    reports: 163,
    lastReported: "2026-02-11",
  },
  // <CHANGE> Adding tiiny.site hosted airdrop scam
  {
    url: "https://pi-airdrop.tiiny.site",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi Network airdrop hosted on tiiny.site free hosting platform",
    reports: 241,
    lastReported: "2026-02-11",
  },
  {
    url: "http://pi-airdrop.tiiny.site",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi Network airdrop hosted on tiiny.site free hosting platform",
    reports: 241,
    lastReported: "2026-02-11",
  },
  // <CHANGE> Adding Vietnamese phishing verification page
  {
    url: "https://chuyendoinetpi.com/verify.php",
    type: "Phishing Verification",
    severity: "critical",
    description: "Vietnamese phishing site with fake Pi Network verification page stealing credentials",
    reports: 195,
    lastReported: "2026-02-11",
  },
  {
    url: "http://chuyendoinetpi.com/verify.php",
    type: "Phishing Verification",
    severity: "critical",
    description: "Vietnamese phishing site with fake Pi Network verification page stealing credentials",
    reports: 195,
    lastReported: "2026-02-11",
  },
  // <CHANGE> Adding new domains found via web search Feb 2026
  {
    url: "https://pi2days.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network 2-day event site stealing user credentials",
    reports: 231,
    lastReported: "2026-02-24",
  },
  {
    url: "http://pi2days.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network 2-day event site stealing user credentials",
    reports: 231,
    lastReported: "2026-02-24",
  },
  {
    url: "https://piexchangetrading.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network exchange and trading platform impersonating official services",
    reports: 344,
    lastReported: "2026-02-24",
  },
  {
    url: "http://piexchangetrading.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network exchange and trading platform impersonating official services",
    reports: 344,
    lastReported: "2026-02-24",
  },
  {
    url: "https://exchange-activate.cc",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fake Pi Network exchange activation site designed to steal wallet credentials",
    reports: 289,
    lastReported: "2026-02-24",
  },
  {
    url: "http://exchange-activate.cc",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fake Pi Network exchange activation site designed to steal wallet credentials",
    reports: 289,
    lastReported: "2026-02-24",
  },
  {
    url: "https://pinets.help",
    type: "Fake Support",
    severity: "critical",
    description: "Fake Pi Network help and support site impersonating official support channels",
    reports: 178,
    lastReported: "2026-02-24",
  },
  {
    url: "http://pinets.help",
    type: "Fake Support",
    severity: "critical",
    description: "Fake Pi Network help and support site impersonating official support channels",
    reports: 178,
    lastReported: "2026-02-24",
  },
  // <CHANGE> Adding user-reported fake drop site
  {
    url: "https://www.pidrop9.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi Network drop site with numbered variant designed to steal user credentials",
    reports: 176,
    lastReported: "2026-03-05",
  },
  {
    url: "http://www.pidrop9.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi Network drop site with numbered variant designed to steal user credentials",
    reports: 176,
    lastReported: "2026-03-05",
  },
  // <CHANGE> Adding English-targeted fake wallet page
  {
    url: "https://2fapinetwallet.com/wallet/index-en",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network wallet page targeting English-speaking users with credential theft",
    reports: 143,
    lastReported: "2026-03-05",
  },
  {
    url: "http://2fapinetwallet.com/wallet/index-en",
    type: "Fake Wallet",
    severity: "critical",
    description: "Fake Pi Network wallet page targeting English-speaking users with credential theft",
    reports: 143,
    lastReported: "2026-03-05",
  },
  // <CHANGE> Adding officially listed scam emails, social accounts and new scam domains from March 2026 web research
  {
    url: "https://fakepidex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fake Pi Network DEX site offering fraudulent 1 Pi = $314 exchange rates to steal wallet credentials",
    reports: 412,
    lastReported: "2026-03-13",
  },
  {
    url: "http://fakepidex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fake Pi Network DEX site offering fraudulent 1 Pi = $314 exchange rates to steal wallet credentials",
    reports: 412,
    lastReported: "2026-03-13",
  },
  {
    url: "https://pinetwork-dex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network DEX impersonating official decentralized exchange services",
    reports: 376,
    lastReported: "2026-03-13",
  },
  {
    url: "http://pinetwork-dex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network DEX impersonating official decentralized exchange services",
    reports: 376,
    lastReported: "2026-03-13",
  },
  {
    url: "https://picoinbonus.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi coin bonus site luring users with free Pi coin offers to steal credentials",
    reports: 284,
    lastReported: "2026-03-13",
  },
  {
    url: "http://picoinbonus.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi coin bonus site luring users with free Pi coin offers to steal credentials",
    reports: 284,
    lastReported: "2026-03-13",
  },
  {
    url: "https://pinetwork-migration.com",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake Pi Network migration site stealing wallet passphrases during open mainnet transition",
    reports: 318,
    lastReported: "2026-03-13",
  },
  {
    url: "http://pinetwork-migration.com",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake Pi Network migration site stealing wallet passphrases during open mainnet transition",
    reports: 318,
    lastReported: "2026-03-13",
  },
  {
    url: "https://pinetwork-kyc.com",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fraudulent Pi KYC verification site impersonating official identity check process",
    reports: 445,
    lastReported: "2026-03-13",
  },
  {
    url: "http://pinetwork-kyc.com",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fraudulent Pi KYC verification site impersonating official identity check process",
    reports: 445,
    lastReported: "2026-03-13",
  },
  {
    url: "https://picoindrop2026.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi coin airdrop site using 2026 branding to appear legitimate and steal credentials",
    reports: 267,
    lastReported: "2026-03-13",
  },
  {
    url: "http://picoindrop2026.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake Pi coin airdrop site using 2026 branding to appear legitimate and steal credentials",
    reports: 267,
    lastReported: "2026-03-13",
  },
  {
    url: "https://pinetwork-support.net",
    type: "Fake Support",
    severity: "critical",
    description: "Fake Pi Network support site impersonating official Pi Care Team to steal user credentials",
    reports: 198,
    lastReported: "2026-03-13",
  },
  {
    url: "http://pinetwork-support.net",
    type: "Fake Support",
    severity: "critical",
    description: "Fake Pi Network support site impersonating official Pi Care Team to steal user credentials",
    reports: 198,
    lastReported: "2026-03-13",
  },
  {
    url: "https://pinetwork-gift.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent Pi Network gift site claiming free Pi coins to phish wallet passphrases",
    reports: 341,
    lastReported: "2026-03-13",
  },
  {
    url: "http://pinetwork-gift.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent Pi Network gift site claiming free Pi coins to phish wallet passphrases",
    reports: 341,
    lastReported: "2026-03-13",
  },
  {
    url: "mailto:C.shorter.69612@mail.ru",
    type: "Scam Email",
    severity: "critical",
    description: "Officially listed scam email address used to target Pi Network users",
    reports: 156,
    lastReported: "2026-03-13",
  },
  {
    url: "mailto:r.fraser.92166@mail.ru",
    type: "Scam Email",
    severity: "critical",
    description: "Officially listed scam email address used to target Pi Network users",
    reports: 143,
    lastReported: "2026-03-13",
  },
  {
    url: "mailto:pinetwork36@hey.com",
    type: "Scam Email",
    severity: "critical",
    description: "Fake Pi Network email account impersonating official Pi Network team",
    reports: 189,
    lastReported: "2026-03-13",
  },
  {
    url: "mailto:PiAssistBot@gmail.com",
    type: "Scam Email",
    severity: "critical",
    description: "Fake Pi Network assistant bot email used for phishing and social engineering",
    reports: 204,
    lastReported: "2026-03-13",
  },
  {
    url: "https://reddit.com/user/throwthemanawayyy",
    type: "Scam Social Account",
    severity: "high",
    description: "Officially listed Reddit scam account targeting Pi Network users",
    reports: 87,
    lastReported: "2026-03-13",
  },
  {
    url: "https://facebook.com/pinetwork.official.009",
    type: "Scam Social Account",
    severity: "critical",
    description: "Fake official Pi Network Facebook page impersonating the Pi Core Team",
    reports: 312,
    lastReported: "2026-03-13",
  },
  {
    url: "https://facebook.com/nicolaskokka.official",
    type: "Scam Social Account",
    severity: "high",
    description: "Fake official Facebook account impersonating a Pi Network figure",
    reports: 176,
    lastReported: "2026-03-13",
  },
  // <CHANGE> Adding fake 2FA Pi Network key site
  {
    url: "https://2fapinetkey.com",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake Pi Network 2FA key site impersonating two-factor authentication to steal passphrase and account credentials. Active victim reported 2026-03-14.",
    reports: 222,
    lastReported: "2026-03-14",
  },
  {
    url: "http://2fapinetkey.com",
    type: "Phishing Verification",
    severity: "critical",
    description: "Fake Pi Network 2FA key site impersonating two-factor authentication to steal passphrase and account credentials. Active victim reported 2026-03-14.",
    reports: 222,
    lastReported: "2026-03-14",
  },
  // </CHANGE> Added fake 2FA Pi Network key site (2 entries with HTTP/HTTPS)
]
