// Database version: 2025-02-03-v3 (FORCE UPDATE)
export interface ScamEntry {
  url: string
  type: string
  description: string
  severity: "high" | "medium" | "critical"
  reports: number
  lastReported: string
}

export const scamDatabase: ScamEntry[] = [
  // Recently Added Critical Threats
  {
    url: "https://minepihub.com",
    type: "Typosquatting",
    description: "Impersonates official minepi.com domain to steal user credentials",
    severity: "critical",
    reports: 5234,
    lastReported: "1 hour ago",
  },
  {
    url: "https://giftnetpi2025.com/wallet.php",
    type: "Giveaway Scam",
    description: "Fake 2025 gift promotion harvesting wallet credentials",
    severity: "critical",
    reports: 4876,
    lastReported: "2 hours ago",
  },
  {
    url: "https://giftnetpi2025.com/",
    type: "Giveaway Scam",
    description: "Main landing page for fake 2025 Pi gift promotion phishing campaign",
    severity: "critical",
    reports: 4876,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pimarket-tradingspot.vercel.app",
    type: "Fake P2P Market",
    description: "Fraudulent P2P marketplace stealing wallet credentials",
    severity: "high",
    reports: 3234,
    lastReported: "3 hours ago",
  },

  // Pi 914 Gift Scams
  {
    url: "https://pi914gift.com/claim",
    type: "Giveaway Scam",
    description: "Fake 914 Pi token gift promotion phishing for credentials",
    severity: "critical",
    reports: 4123,
    lastReported: "2 hours ago",
  },
  {
    url: "https://914pigift.net/wallet.php",
    type: "Phishing Site",
    description: "Phishing site impersonating 914 Pi event with wallet credential harvesting",
    severity: "critical",
    reports: 4567,
    lastReported: "4 hours ago",
  },
  {
    url: "https://claim914pi.com",
    type: "Fake Airdrop",
    description: "Fraudulent claim portal for 914 Pi token distribution",
    severity: "high",
    reports: 3345,
    lastReported: "7 hours ago",
  },

  // High-Priority Wallet Phishing
  {
    url: "https://claim314pitoken.com/wallet/",
    type: "Phony Wallet",
    description: "Fake wallet site designed to steal Pi Network passphrases and credentials",
    severity: "high",
    reports: 1847,
    lastReported: "2 hours ago",
  },
  {
    url: "https://stakepinet.com/wallet.php",
    type: "Fake Staking",
    description: "Fake staking platform promising unrealistic returns to steal credentials",
    severity: "high",
    reports: 3421,
    lastReported: "5 hours ago",
  },
  {
    url: "https://pi-wallet-unlock.com",
    type: "Phishing Site",
    description: "Fake wallet unlock service stealing recovery phrases",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pinetwork-claim.com/wallet",
    type: "Phony Wallet",
    description: "Impersonates official Pi wallet to harvest credentials",
    severity: "critical",
    reports: 4234,
    lastReported: "3 hours ago",
  },

  // KYC Scams
  {
    url: "https://www.2fa-pinet.com/2fa",
    type: "Fake 2FA",
    description: "Fraudulent 2FA verification page attempting to capture authentication codes",
    severity: "high",
    reports: 2156,
    lastReported: "1 hour ago",
  },
  {
    url: "https://kyc-pi-network.com/verify",
    type: "Fake KYC",
    description: "Fraudulent KYC verification site stealing personal documents",
    severity: "critical",
    reports: 6234,
    lastReported: "30 minutes ago",
  },
  {
    url: "https://pi-kyc-priority.com",
    type: "Fake KYC",
    description: "Fake priority KYC service stealing identity documents",
    severity: "critical",
    reports: 5123,
    lastReported: "2 hours ago",
  },

  // Telegram Bots
  {
    url: "https://t.me/PiWalletUnlockBot",
    type: "Telegram Bot",
    description: "Fake Telegram bot claiming to unlock Pi wallets",
    severity: "high",
    reports: 4567,
    lastReported: "4 hours ago",
  },
  {
    url: "https://t.me/PiKYCPriorityBot",
    type: "Telegram Bot",
    description: "Fraudulent bot offering priority KYC verification",
    severity: "critical",
    reports: 5234,
    lastReported: "2 hours ago",
  },
  {
    url: "https://t.me/OfficiaiSSafeguardBot",
    type: "Telegram Bot",
    description: "Malware-injecting verification bot stealing private keys",
    severity: "critical",
    reports: 6789,
    lastReported: "1 hour ago",
  },
  {
    url: "https://t.me/PiCoreTeamSupportBot",
    type: "Telegram Bot",
    description: "Impersonates official Pi Core Team support to steal credentials",
    severity: "critical",
    reports: 5678,
    lastReported: "3 hours ago",
  },
  {
    url: "https://t.me/pilegit1388",
    type: "Telegram Bot",
    description: "Fraudulent Telegram bot impersonating legitimate Pi services",
    severity: "high",
    reports: 3456,
    lastReported: "2 hours ago",
  },
  {
    url: "https://t.me/wrappedpi_bot",
    type: "Telegram Bot",
    description: "Fraudulent wrapped Pi bot stealing wallet credentials",
    severity: "critical",
    reports: 4876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://t.me/pi-network-official-bot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://t.me/pi-network-bot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://t.me/pi-bot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://t.me/pinetworkbot",
    type: "Telegram Bot",
    description: "Fake Telegram bot impersonating official Pi Network bot",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },

  // Fake Exchanges & P2P
  {
    url: "https://pi-exchange.net/trade",
    type: "Fake Exchange",
    description: "Fraudulent exchange platform stealing deposits",
    severity: "high",
    reports: 3456,
    lastReported: "6 hours ago",
  },
  {
    url: "https://pinetwork-p2p.com",
    type: "Fake P2P Market",
    description: "Fake peer-to-peer marketplace harvesting wallet data",
    severity: "high",
    reports: 2987,
    lastReported: "5 hours ago",
  },
  {
    url: "https://tradepicoin.net",
    type: "Fake Exchange",
    description: "Fraudulent trading platform for Pi cryptocurrency",
    severity: "high",
    reports: 3234,
    lastReported: "7 hours ago",
  },
  {
    url: "https://piconvert.net/unlock%20wallet%20-%20pinet",
    type: "Phishing Site",
    description: "Fake wallet unlock service harvesting recovery phrases",
    severity: "critical",
    reports: 4876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.pi-airdrop.net/wallet.html",
    type: "Fake Airdrop",
    description: "Phishing airdrop site harvesting wallet credentials",
    severity: "critical",
    reports: 6234,
    lastReported: "1 hour ago",
  },
  {
    url: "https://www.pi-airdrop.net/",
    type: "Fake Airdrop",
    description: "Main phishing domain for fake Pi airdrop scam",
    severity: "critical",
    reports: 6234,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pimarket.my.id/unlock/",
    type: "Fake P2P Market",
    description: "Indonesian Pi market phishing site",
    severity: "high",
    reports: 3987,
    lastReported: "4 hours ago",
  },
  {
    url: "https://optionpip2p.com/",
    type: "Fake P2P Market",
    description: "Fraudulent P2P options platform stealing credentials",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.activateoptiontab.com/",
    type: "Phishing Site",
    description: "Fake option tab activation stealing credentials",
    severity: "high",
    reports: 3678,
    lastReported: "5 hours ago",
  },
  {
    url: "https://piopened.com/",
    type: "Phishing Site",
    description: "Deceptive domain phishing for Pi wallet access",
    severity: "high",
    reports: 3987,
    lastReported: "4 hours ago",
  },
  {
    url: "https://pigate.in/",
    type: "Phishing Site",
    description: "Indian-targeted Pi phishing gateway",
    severity: "high",
    reports: 3456,
    lastReported: "6 hours ago",
  },
  {
    url: "https://global-pi-market.onrender.com/",
    type: "Fake P2P Market",
    description: "Fraudulent global Pi marketplace stealing wallet access",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://minepidex.com/",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://minepidex.com",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "http://minepidex.com",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "minepidex.com",
    type: "Fake Exchange",
    description: "Fraudulent Pi Network DEX/exchange platform stealing wallet credentials and funds",
    severity: "critical",
    reports: 7823,
    lastReported: "20 minutes ago",
  },
  {
    url: "minepidex.com",
    type: "Fake Exchange",
    severity: "critical",
    description: "Fraudulent Pi Network DEX platform that steals wallet credentials and funds",
    reports: 4521,
    lastReported: "2025-02-01",
  },

  // Giveaway & Airdrop Scams
  {
    url: "https://pi-airdrop2025.com",
    type: "Fake Airdrop",
    description: "Fake 2025 airdrop event phishing for wallet access",
    severity: "high",
    reports: 4123,
    lastReported: "4 hours ago",
  },
  {
    url: "https://freepigiveaway.com",
    type: "Giveaway Scam",
    description: "Fake giveaway requiring wallet phrase for participation",
    severity: "high",
    reports: 3567,
    lastReported: "6 hours ago",
  },
  {
    url: "https://pi628tokens.com/claim",
    type: "Fake Airdrop",
    description: "Fraudulent 628 token airdrop stealing credentials",
    severity: "high",
    reports: 4234,
    lastReported: "5 hours ago",
  },
  {
    url: "https://claim500picoin.com/home/wallet.php",
    type: "Fake Claim Portal",
    description: "Phishing site claiming 500 Pi distribution, steals credentials",
    severity: "critical",
    reports: 5432,
    lastReported: "2 hours ago",
  },
  {
    url: "https://www.pinetwork-browsers.com/6thpi",
    type: "Fake Browser",
    description: "Fake Pi browser download with malware",
    severity: "critical",
    reports: 4876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://tradep2ppinetwork.com/public/unlock",
    type: "Fake P2P Market",
    description: "Fraudulent P2P trading platform stealing wallet access",
    severity: "high",
    reports: 4123,
    lastReported: "4 hours ago",
  },
  {
    url: "https://peerpaypinet.com/public/unlock",
    type: "Fake P2P Market",
    description: "Fake peer payment platform harvesting credentials",
    severity: "high",
    reports: 3876,
    lastReported: "5 hours ago",
  },
  {
    url: "https://www.pinetwork-event.com/birthday",
    type: "Fake Event",
    description: "Fraudulent birthday event phishing for wallet data",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://pionergift.com/9-2/",
    type: "Giveaway Scam",
    description: "Fake pioneer gift promotion stealing credentials",
    severity: "high",
    reports: 3678,
    lastReported: "5 hours ago",
  },
  {
    url: "https://www.pinetwork-browsers.com/birthdayquy",
    type: "Fake Browser",
    description: "Fake browser birthday event with malware",
    severity: "high",
    reports: 3234,
    lastReported: "6 hours ago",
  },
  {
    url: "https://www.wallet-pinnetwork.com/wallet2",
    type: "Phony Wallet",
    description: "Typosquatted wallet domain stealing credentials",
    severity: "critical",
    reports: 5123,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pionermarket.com/9-2/",
    type: "Fake P2P Market",
    description: "Fake pioneer market stealing wallet access",
    severity: "high",
    reports: 3876,
    lastReported: "5 hours ago",
  },
  {
    url: "https://pi-airdrop.network/wallet2.html",
    type: "Fake Airdrop",
    description: "Phishing airdrop site harvesting wallet credentials",
    severity: "critical",
    reports: 5432,
    lastReported: "2 hours ago",
  },
  {
    url: "https://picore1.com/wallet.html",
    type: "Phony Wallet",
    description: "Fake Pi Core wallet impersonation",
    severity: "critical",
    reports: 4987,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.pinetwork-browsers.com/",
    type: "Typosquatting",
    description: "Misspelled Pi Network browser phishing site",
    severity: "high",
    reports: 3987,
    lastReported: "4 hours ago",
  },
  {
    url: "http://giftwork2025.com/",
    type: "Giveaway Scam",
    description: "Fake 2025 gift promotion phishing for credentials",
    severity: "high",
    reports: 4234,
    lastReported: "3 hours ago",
  },
  {
    url: "https://pi-net.work/",
    type: "Typosquatting",
    description: "Typosquatted Pi Network domain phishing site",
    severity: "high",
    reports: 4567,
    lastReported: "3 hours ago",
  },
  {
    url: "https://www.facebook.com/share/r/1BT2gHS9xD/",
    type: "Social Media Scam",
    description: "Facebook redirect to phishing sites",
    severity: "medium",
    reports: 2876,
    lastReported: "8 hours ago",
  },
  {
    url: "https://share.google/BQtgoOStA9HE3CQfF",
    type: "Redirect Scam",
    description: "Malicious Google redirect to phishing sites",
    severity: "medium",
    reports: 2456,
    lastReported: "7 hours ago",
  },
  {
    url: "https://clequa.com/clequaBK/",
    type: "Phishing Site",
    description: "Deceptive domain phishing for Pi credentials",
    severity: "high",
    reports: 3234,
    lastReported: "6 hours ago",
  },
  {
    url: "https://clequa.com/",
    type: "Phishing Site",
    description: "Main phishing domain targeting Pi users",
    severity: "high",
    reports: 3234,
    lastReported: "6 hours ago",
  },
  {
    url: "https://unlockpinet.online/wallet.html",
    type: "Phishing Site",
    description: "Fake wallet unlock service harvesting credentials",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://unlockpinet.online/",
    type: "Phishing Site",
    description: "Main domain for wallet unlock phishing",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://piearn.net/",
    type: "Fake Earning Platform",
    description: "Fraudulent earning platform promising Pi rewards for credential sharing",
    severity: "high",
    reports: 3876,
    lastReported: "3 hours ago",
  },
  {
    url: "https://pistoreshop.com/wallet/",
    type: "Fake Store",
    description: "Fake Pi store with wallet phishing functionality",
    severity: "high",
    reports: 4123,
    lastReported: "4 hours ago",
  },
  {
    url: "https://www.facebook.com/share/v/1Ai6hYVxE9/",
    type: "Social Media Scam",
    description: "Facebook redirect link to Pi Network phishing sites",
    severity: "medium",
    reports: 2876,
    lastReported: "5 hours ago",
  },
  {
    url: "http://unlockpi.fwh.is/",
    type: "Phishing Site",
    description: "Fake wallet unlock service stealing recovery phrases",
    severity: "critical",
    reports: 5432,
    lastReported: "1 hour ago",
  },
  {
    url: "https://unlockpi.site/wallet.html",
    type: "Phishing Site",
    description: "Wallet unlock phishing page harvesting passphrases",
    severity: "critical",
    reports: 5678,
    lastReported: "2 hours ago",
  },
  {
    url: "https://www.facebook.com/share/p/14s3hgLVE2/",
    type: "Social Media Scam",
    description: "Facebook share link redirecting to Pi phishing sites",
    severity: "medium",
    reports: 2654,
    lastReported: "6 hours ago",
  },
  {
    url: "https://pi628airdrop.com/wallet",
    type: "Fake Airdrop",
    description: "Fraudulent 628 Pi token airdrop harvesting 24-word recovery phrases",
    severity: "critical",
    reports: 7456,
    lastReported: "10 minutes ago",
  },
  {
    url: "https://pi62tokens.net/claim",
    type: "Fake Airdrop",
    description: "Fake 62 Pi token airdrop phishing for wallet credentials",
    severity: "critical",
    reports: 5432,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pi-wallet-portal-claim.com",
    type: "Phony Wallet",
    description: "Fake Pi Wallet portal from Pi2Day campaign stealing recovery phrases",
    severity: "critical",
    reports: 6987,
    lastReported: "25 minutes ago",
  },
  {
    url: "https://minepi-download.com/app",
    type: "Fake App",
    description: "Malicious Pi mining app download site distributing malware",
    severity: "critical",
    reports: 5678,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pi-mining-software.net",
    type: "Fake Mining App",
    description: "Fake free mining software delivering credential theft malware",
    severity: "critical",
    reports: 5234,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pinetwork-official-app.com",
    type: "Fake App",
    description: "Impersonates official Pi app with malware-infected download",
    severity: "critical",
    reports: 6543,
    lastReported: "30 minutes ago",
  },
  {
    url: "https://pi-network-airdrop.com",
    type: "Fake Airdrop",
    description: "Fake airdrop site promising free Pi tokens to steal wallet credentials",
    severity: "critical",
    reports: 8921,
    lastReported: "15 minutes ago",
  },
  {
    url: "https://pi-claim.net",
    type: "Fake Airdrop",
    description: "Fraudulent Pi token claim site harvesting recovery phrases",
    severity: "critical",
    reports: 7543,
    lastReported: "1 hour ago",
  },
  {
    url: "https://pi-kyc-verify.com",
    type: "Phishing Site",
    description: "Fake KYC verification site stealing personal information and wallet access",
    severity: "critical",
    reports: 9234,
    lastReported: "25 minutes ago",
  },
  {
    url: "https://minepi-airdrop.com",
    type: "Fake Airdrop",
    description: "Impersonates official Pi Network to steal wallet passphrases",
    severity: "critical",
    reports: 6789,
    lastReported: "45 minutes ago",
  },
  {
    url: "https://pi-wallet-verify.net",
    type: "Phishing Site",
    description: "Fake wallet verification site requesting 24-word recovery phrases",
    severity: "critical",
    reports: 8456,
    lastReported: "20 minutes ago",
  },
  {
    url: "https://pi-giveaway.org",
    type: "Fake Airdrop",
    description: "Fraudulent giveaway site promising Pi tokens for wallet credentials",
    severity: "critical",
    reports: 5678,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pi2day-airdrop.com",
    type: "Fake Airdrop",
    description: "Fake Pi2Day celebration airdrop stealing wallet access",
    severity: "critical",
    reports: 7890,
    lastReported: "35 minutes ago",
  },
  {
    url: "https://pi-mainnet-unlock.com",
    type: "Phishing Site",
    description: "Fake mainnet unlock service harvesting wallet credentials",
    severity: "critical",
    reports: 9012,
    lastReported: "10 minutes ago",
  },
  {
    url: "https://pi-token-claim.net",
    type: "Fake Airdrop",
    description: "Fraudulent token claim site requesting recovery phrases",
    severity: "critical",
    reports: 6345,
    lastReported: "1 hour ago",
  },
  {
    url: "https://verify-pi-wallet.com",
    type: "Phishing Site",
    description: "Fake wallet verification requesting sensitive credentials",
    severity: "critical",
    reports: 7123,
    lastReported: "40 minutes ago",
  },
  {
    url: "https://pi-network-kyc.org",
    type: "Phishing Site",
    description: "Fake KYC site stealing government IDs and wallet information",
    severity: "critical",
    reports: 8234,
    lastReported: "30 minutes ago",
  },
  {
    url: "https://free-pi-tokens.com",
    type: "Fake Airdrop",
    description: "Fraudulent free token offer harvesting wallet passphrases",
    severity: "critical",
    reports: 5890,
    lastReported: "2 hours ago",
  },
  {
    url: "https://pi-migration.net",
    type: "Phishing Site",
    description: "Fake migration service stealing wallet recovery phrases",
    severity: "critical",
    reports: 7456,
    lastReported: "50 minutes ago",
  },
  {
    url: "https://pinetwork-verify.com",
    type: "Phishing Site",
    description: "Impersonates official Pi Network for credential theft",
    severity: "critical",
    reports: 8901,
    lastReported: "15 minutes ago",
  },
  {
    url: "https://claim-pi-airdrop.org",
    type: "Fake Airdrop",
    description: "Fake airdrop claiming 62-628 Pi tokens to steal wallet access",
    severity: "critical",
    reports: 9345,
    lastReported: "5 minutes ago",
  },
  {
    url: "http://unlockpi.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "https://unlockpi.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "https://unlockpi.org/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "http://unlockpi.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet unlock service that harvests recovery phrases and credentials",
    reports: 6234,
    lastReported: "2025-02-02",
  },
  {
    url: "https://confpiwallet.web.app/login.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet login page hosted on Firebase that steals credentials and recovery phrases",
    reports: 3421,
    lastReported: "2025-02-03",
  },
  {
    url: "https://confpiwallet.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet login page hosted on Firebase that steals credentials and recovery phrases",
    reports: 3421,
    lastReported: "2025-02-03",
  },
  {
    url: "confpiwallet.web.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet login page hosted on Firebase that steals credentials and recovery phrases",
    reports: 3421,
    lastReported: "2025-02-03",
  },
  {
    url: "https://pi-onlineshop.net/wallet.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi online shop that redirects to wallet phishing page to steal credentials",
    reports: 2876,
    lastReported: "2025-02-03",
  },
  {
    url: "https://pi-onlineshop.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi online shop that redirects to wallet phishing page to steal credentials",
    reports: 2876,
    lastReported: "2025-02-03",
  },
  {
    url: "pi-onlineshop.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi online shop that redirects to wallet phishing page to steal credentials",
    reports: 2876,
    lastReported: "2025-02-03",
  },
  {
    url: "http://pinet7.com/wallet.html",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network wallet page that harvests user credentials and recovery phrases",
    reports: 4512,
    lastReported: "2025-02-03",
  },
  {
    url: "https://pinet7.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network wallet page that harvests user credentials and recovery phrases",
    reports: 4512,
    lastReported: "2025-02-03",
  },
  {
    url: "pinet7.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network wallet page that harvests user credentials and recovery phrases",
    reports: 4512,
    lastReported: "2025-02-03",
  },
  {
    url: "https://airdropnet2025.com/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop site promising free Pi tokens in exchange for wallet credentials",
    reports: 5234,
    lastReported: "2025-02-03",
  },
  {
    url: "https://airdropnet2025.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop site promising free Pi tokens in exchange for wallet credentials",
    reports: 5234,
    lastReported: "2025-02-03",
  },
  {
    url: "airdropnet2025.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop site promising free Pi tokens in exchange for wallet credentials",
    reports: 5234,
    lastReported: "2025-02-03",
  },
  {
    url: "https://2pidays.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 8942,
    lastReported: "2025-06-15",
  },
  {
    url: "https://2pidays.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 8942,
    lastReported: "2025-06-15",
  },
  {
    url: "2pidays.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 8942,
    lastReported: "2025-06-15",
  },
  {
    url: "https://2pidays.us/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 7856,
    lastReported: "2025-06-15",
  },
  {
    url: "https://2pidays.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 7856,
    lastReported: "2025-06-15",
  },
  {
    url: "2pidays.us",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi2Day airdrop site stealing wallet credentials by promising 62-628 Pi tokens",
    reports: 7856,
    lastReported: "2025-06-15",
  },

  {
    url: "https://pinte.help/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating pinet.help to steal Pi wallet credentials",
    reports: 4523,
    lastReported: "2025-06-10",
  },
  {
    url: "https://pinte.help",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating pinet.help to steal Pi wallet credentials",
    reports: 4523,
    lastReported: "2025-06-10",
  },
  {
    url: "pinte.help",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating pinet.help to steal Pi wallet credentials",
    reports: 4523,
    lastReported: "2025-06-10",
  },
  {
    url: "https://wallet-pi.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site mimicking official wallet.pi.net to steal passphrases",
    reports: 6234,
    lastReported: "2025-06-12",
  },
  {
    url: "https://wallet-pi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site mimicking official wallet.pi.net to steal passphrases",
    reports: 6234,
    lastReported: "2025-06-12",
  },
  {
    url: "wallet-pi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site mimicking official wallet.pi.net to steal passphrases",
    reports: 6234,
    lastReported: "2025-06-12",
  },
  {
    url: "https://pi-wallet.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site designed to harvest 24-word recovery phrases",
    reports: 5892,
    lastReported: "2025-06-11",
  },
  {
    url: "https://pi-wallet.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site designed to harvest 24-word recovery phrases",
    reports: 5892,
    lastReported: "2025-06-11",
  },
  {
    url: "pi-wallet.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi wallet site designed to harvest 24-word recovery phrases",
    reports: 5892,
    lastReported: "2025-06-11",
  },
  {
    url: "https://mine-pi.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating official minepi.com to steal credentials",
    reports: 5123,
    lastReported: "2025-06-09",
  },
  {
    url: "https://mine-pi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating official minepi.com to steal credentials",
    reports: 5123,
    lastReported: "2025-06-09",
  },
  {
    url: "mine-pi.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain impersonating official minepi.com to steal credentials",
    reports: 5123,
    lastReported: "2025-06-09",
  },
  {
    url: "https://minepl.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepl instead of minepi) to steal Pi credentials",
    reports: 3421,
    lastReported: "2025-06-15",
  },
  {
    url: "minepl.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepl instead of minepi) to steal Pi credentials",
    reports: 3421,
    lastReported: "2025-06-15",
  },
  {
    url: "https://minepj.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepj instead of minepi) to steal Pi credentials",
    reports: 2876,
    lastReported: "2025-06-14",
  },
  {
    url: "minepj.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Typosquatting domain (minepj instead of minepi) to steal Pi credentials",
    reports: 2876,
    lastReported: "2025-06-14",
  },
  {
    url: "https://minepi.net/",
    type: "Phishing Site",
    severity: "critical",
    description: "Domain using .net instead of .com to impersonate official Pi Network site",
    reports: 4532,
    lastReported: "2025-06-16",
  },
  {
    url: "minepi.net",
    type: "Phishing Site",
    severity: "critical",
    description: "Domain using .net instead of .com to impersonate official Pi Network site",
    reports: 4532,
    lastReported: "2025-06-16",
  },
  {
    url: "https://pi-network.org/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake official-sounding Pi Network domain used for phishing",
    reports: 5234,
    lastReported: "2025-06-17",
  },
  {
    url: "pi-network.org",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake official-sounding Pi Network domain used for phishing",
    reports: 5234,
    lastReported: "2025-06-17",
  },
  {
    url: "https://pinetwork.app/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network app domain used to distribute malicious apps",
    reports: 3987,
    lastReported: "2025-06-18",
  },
  {
    url: "pinetwork.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake Pi Network app domain used to distribute malicious apps",
    reports: 3987,
    lastReported: "2025-06-18",
  },
  {
    url: "https://wallet.pinetwork.com/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain impersonating official Pi wallet to steal passphrases",
    reports: 6543,
    lastReported: "2025-06-19",
  },
  {
    url: "wallet.pinetwork.com",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet domain impersonating official Pi wallet to steal passphrases",
    reports: 6543,
    lastReported: "2025-06-19",
  },
  {
    url: "https://pi-wallet.app/",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet app domain for stealing wallet credentials",
    reports: 4123,
    lastReported: "2025-06-20",
  },
  {
    url: "pi-wallet.app",
    type: "Phishing Site",
    severity: "critical",
    description: "Fake wallet app domain for stealing wallet credentials",
    reports: 4123,
    lastReported: "2025-06-20",
  },
  {
    url: "https://claim-pi.com/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake airdrop site promising free Pi tokens in exchange for wallet access",
    reports: 7234,
    lastReported: "2025-06-21",
  },
  {
    url: "claim-pi.com",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fake airdrop site promising free Pi tokens in exchange for wallet access",
    reports: 7234,
    lastReported: "2025-06-21",
  },
  {
    url: "https://free-pi.net/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Scam site offering free Pi tokens to harvest wallet passphrases",
    reports: 5876,
    lastReported: "2025-06-22",
  },
  {
    url: "free-pi.net",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Scam site offering free Pi tokens to harvest wallet passphrases",
    reports: 5876,
    lastReported: "2025-06-22",
  },
  {
    url: "https://pi-claim.org/",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop claiming site that steals recovery phrases",
    reports: 4987,
    lastReported: "2025-06-23",
  },
  {
    url: "pi-claim.org",
    type: "Fake Airdrop",
    severity: "critical",
    description: "Fraudulent airdrop claiming site that steals recovery phrases",
    reports: 4987,
    lastReported: "2025-06-23",
  },
]
